/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/scene.gltf 
Author: glcalde (https://sketchfab.com/glcalde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-computer-d62ac723c3fe44b983acc9c2e38e5138
Title: Low Poly Computer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert4SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
